import { useState, useEffect } from "react";
import api from "../services/api";

import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import SearchBox from "../components/SearchBox";
import DecisionCard from "../components/DecisionCard";
import ConfidenceCard from "../components/ConfidenceCard";
import SummaryCard from "../components/SummaryCard";
import KeyFactors from "../components/KeyFactors";
import Stats from "../components/Stats";
import HistoryCard from "../components/HistoryCard";
import Loader from "../components/Loader";
import EmptyState from "../components/EmptyState";
import Disclaimer from "../components/Disclaimer";
import { FaExclamationTriangle, FaFilePdf } from "react-icons/fa";

function Dashboard() {
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(false);
  const [researchError, setResearchError] = useState("");

  async function loadHistory() {
    try {
      const res = await api.get("/research");
      if (res.data.success) {
        setHistory(res.data.history);
      }
    } catch (err) {
      console.log(err);
    }
  }

  useEffect(() => {
    let ignore = false;

    api.get("/research")
      .then((res) => {
        if (!ignore && res.data.success) {
          setHistory(res.data.history);
        }
      })
      .catch((err) => console.log(err));

    return () => {
      ignore = true;
    };
  }, []);

  const handleResearch = async (company) => {
    if (!company.trim()) {
      setResearchError("Please enter a company name.");
      return;
    }

    try {
      setLoading(true);
      setResult(null);
      setResearchError("");

      const res = await api.post("/research", { company });

      if (res.data.success) {
        setResult(res.data);
        loadHistory();
      }
    } catch (err) {
      console.log(err);
      setResearchError(err.response?.data?.message || "Research Failed");
    } finally {
      setLoading(false);
    }
  };

  const handleSelectHistory = (item) => {
    setResult(item);
    setResearchError("");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const handlePrintReport = () => {
    if (!result) return;
    
    const printWindow = window.open("", "_blank");
    const factorsHtml = result.factors.map(f => `<li>${f}</li>`).join("");
    const decisionColor = result.decision === "INVEST" ? "#10b981" : "#ef4444";
    const dateStr = new Date(result.createdAt || Date.now()).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit"
    });

    printWindow.document.write(`
      <html>
        <head>
          <title>${result.company} - Investment Research Report</title>
          <style>
            body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; padding: 40px; line-height: 1.6; max-width: 800px; margin: 0 auto; }
            .header { border-bottom: 3px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
            .title { font-size: 28px; font-weight: 800; color: #0f172a; margin: 0; }
            .subtitle { font-size: 14px; color: #64748b; margin-top: 5px; }
            .meta-grid { display: grid; grid-template-cols: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
            .meta-card { background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; }
            .meta-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; font-weight: bold; }
            .meta-value { font-size: 20px; font-weight: bold; margin-top: 5px; }
            .section-title { font-size: 18px; font-weight: bold; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; margin-top: 30px; margin-bottom: 15px; color: #0f172a; }
            .summary { font-size: 14px; color: #334155; }
            .factors-list { padding-left: 20px; margin: 0; }
            .factors-list li { margin-bottom: 10px; font-size: 14px; color: #334155; }
            .footer { border-top: 1px solid #e2e8f0; padding-top: 20px; margin-top: 50px; font-size: 11px; color: #94a3b8; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1 class="title">AI Investment Research Report</h1>
            <div class="subtitle">Generated by AI Research Agent Platform • ${dateStr}</div>
          </div>
          
          <div class="meta-grid">
            <div class="meta-card">
              <div class="meta-label">Company Target</div>
              <div class="meta-value">${result.company}</div>
            </div>
            <div class="meta-card">
              <div class="meta-label">Recommendation</div>
              <div class="meta-value" style="color: ${decisionColor}">${result.decision}</div>
            </div>
            <div class="meta-card">
              <div class="meta-label">Confidence Rating</div>
              <div class="meta-value">${result.confidence}%</div>
            </div>
            <div class="meta-card">
              <div class="meta-label">Orchestration Model</div>
              <div class="meta-value" style="font-size: 14px; margin-top: 10px;">${result.modelUsed || "gemini-2.5-flash (LangGraph)"}</div>
            </div>
          </div>

          <div class="section-title">Research Summary</div>
          <div class="summary">${result.summary}</div>

          <div class="section-title">Investment Thesis & Drivers</div>
          <div class="summary">${result.reason}</div>

          <div class="section-title">Core Evaluation Factors</div>
          <ul class="factors-list">
            ${factorsHtml}
          </ul>

          <div class="footer">
            Disclaimer: This document is an automated AI-generated report. It does not constitute professional financial advice. Invest at your own risk.
          </div>
          
          <script>
            window.onload = function() {
              window.print();
              setTimeout(function() { window.close(); }, 500);
            }
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  const total = history.length;
  const invest = history.filter((item) => item.decision === "INVEST").length;
  const pass = history.filter((item) => item.decision === "PASS").length;

  return (
    <div className="flex bg-slate-900 min-h-screen text-slate-100">
      <Sidebar />

      <div className="flex-1 ml-64 p-8 overflow-y-auto">
        <Navbar />

        <div className="mt-6">
          <Stats total={total} invest={invest} pass={pass} />
        </div>

        <div className="mt-6">
          <SearchBox handleResearch={handleResearch} loading={loading} />
        </div>

        {researchError && !loading && (
          <div className="mt-6 rounded-2xl border border-amber-400/25 bg-amber-950/30 p-5 text-amber-100 shadow-lg shadow-amber-950/20">
            <div className="flex items-start gap-3">
              <FaExclamationTriangle className="mt-0.5 text-amber-300" />
              <div>
                <h3 className="text-sm font-bold text-amber-100">Research could not run</h3>
                <p className="mt-1 text-sm text-amber-200/90">{researchError}</p>
              </div>
            </div>
          </div>
        )}

        {loading ? (
          <Loader />
        ) : result ? (
          <>
            {/* Action Bar for export */}
            <div className="flex justify-end mt-6">
              <button
                onClick={handlePrintReport}
                className="flex items-center gap-2 bg-gradient-to-r from-blue-600 to-cyan-500 hover:from-blue-500 hover:to-cyan-400 text-white px-4 py-2.5 rounded-xl font-bold text-xs shadow-lg hover:shadow-xl transition-all duration-200 hover:-translate-y-0.5"
              >
                <FaFilePdf /> Export PDF Report
              </button>
            </div>

            <div className="grid lg:grid-cols-2 gap-6 mt-4">
              <DecisionCard result={result} />
              <ConfidenceCard confidence={result.confidence} />
            </div>

            <div className="grid lg:grid-cols-2 gap-6 mt-6">
              <KeyFactors result={result} />
              <SummaryCard result={result} />
            </div>

            <div className="mt-6">
              <Disclaimer />
            </div>
          </>
        ) : (
          <div className="mt-6">
            <EmptyState />
          </div>
        )}

        <div className="mt-6">
          <HistoryCard
            history={history}
            loadHistory={loadHistory}
            onSelect={handleSelectHistory}
          />
        </div>
      </div>
    </div>
  );
}

export default Dashboard;
